android {
    namespace 'de.florianisme.wakeonlan'
    compileSdk 37

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
        }
        debug {
            minifyEnabled true
            shrinkResources true
        }
    }

    defaultConfig {
        applicationId "de.florianisme.wakeonlan"
        minSdk 25
        targetSdk 37
        versionName "1.9.8"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.support:wearable:2.9.0'
    compileOnly 'com.google.android.wearable:wearable:2.9.0'
    implementation 'com.google.android.gms:play-services-wearable:20.0.1'

    implementation 'com.google.guava:guava:33.6.0-jre'

    implementation 'com.google.code.gson:gson:2.14.0'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:5.23.0'
}