apply plugin: 'com.android.application'
apply from: "$rootProject.projectDir/shared-build.gradle"

android {
    compileSdk 37
    defaultConfig {
        targetSdk 37
        versionCode 110
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "androidx.core:core-splashscreen:1.2.0"

    implementation 'androidx.wear:wear:1.4.0'
    implementation 'androidx.wear.compose:compose-foundation:1.6.2'
    implementation 'androidx.wear.compose:compose-material:1.6.2'

    implementation project(path: ':shared-models')
}