apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply from: "$rootProject.projectDir/shared-build.gradle"

android {
    compileSdk 37
    defaultConfig {
        targetSdk 37
        versionCode 118
    }
    buildFeatures {
        compose true
    }
}

dependencies {
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.core.splashscreen

    implementation libs.androidx.wear

    // Jetpack Compose (Wear)
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose.core
    implementation libs.androidx.activity.compose
    implementation libs.bundles.wearable.compose
    debugImplementation libs.bundles.compose.debug

    implementation project(path: ':shared-models')
}