apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply from: "$rootProject.projectDir/shared-build.gradle"

android {
    defaultConfig {
        versionCode 119
        wearAppUnbundled true
    }
    buildFeatures {
        compose true
    }

    packaging {
        resources {
            excludes += 'META-INF/LICENSE.md'
        }
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.google.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui
    implementation libs.androidx.swiperefreshlayout

    // Jetpack Compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose.core
    implementation libs.androidx.activity.compose
    implementation libs.androidx.navigation.compose
    implementation libs.androidx.lifecycle.runtime.compose
    implementation libs.androidx.compose.runtime.livedata
    debugImplementation libs.bundles.compose.debug

    implementation libs.reactive.streams
    implementation libs.rxjava2

    implementation libs.androidx.core
    implementation libs.androidx.core.google.shortcuts

    implementation libs.androidx.room.runtime
    annotationProcessor libs.androidx.room.compiler

    implementation libs.bundles.lifecycle

    // SSH
    implementation libs.sshj
    implementation libs.bundles.security

    implementation project(path: ':shared-models')
    implementation project(path: ':ping')

    // Kotlin BOM
    implementation platform(libs.kotlin.bom)
}