apply plugin: 'com.android.library'

android {
    namespace 'de.florianisme.wakeonlan.ping'
    compileSdk 37

    defaultConfig {
        minSdk 24
        targetSdk 37
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
